package challenger;

import java.math.BigInteger;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class FibonacciNumbersSum {

    public static void main(String[] args) {
        System.out.println(Fibonacci.sumFibonacciNumbers(4000000));
    }

    private static class Fibonacci{

        private static BigInteger sumFibonacciNumbers(int n){
            BigInteger total = BigInteger.valueOf(2);
            int i = 1;
            int x = 2;
            int aux;
            while (x <= n){
                aux = x;
                x = x + i;
                i = aux;
                if(x < n && x % 2 == 0)
                    total = total.add(BigInteger.valueOf(x));
            }
            return total;
        }

    }

}
